global:
  resolve_timeout: 5m

route:
  receiver: console

  routes:
    - matchers:
        - team="dev"
      receiver: dev

    - matchers:
        - team="infra"
      receiver: infra

receivers:
  - name: dev

  - name: infra

  - name: console
