services:
  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    ports:
      - "9090:9090"


  node_exporter:
    image: prom/node-exporter:v1.8.0
    ports:
      - "9100:9100"

  app:
    build: ./app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
